Quizistic/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('<slug:category_slug>/', views.home, name='home_cat'),
    path('account/', include('account.urls')),
    path('quiz/', include('quiz.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path('all-quiz/', views.all_quiz_view, name='all_quiz'),
    path('category/<slug:category_slug>/', views.all_quiz_view, name='cat_quiz'),
    path('question/<int:q_id>/', views.question_view, name='question'),
    path('submit-answer/<int:q_id>/<int:ques_id>/', views.submit_answer_view, name='submit_answer'),
    path('result/<int:quiz_id>/<int:user_id>/<int:q_id>/', views.result_after_quiz, name='quiz-result'),
    path('result/', views.result, name='result'),
    path('ratings/<int:id>/', views.RatingsView.as_view(), name='ratings'),
    
  

]

quiz/models.py
from django.db import models
from category.models import Category
from django.contrib.auth.models import User
# from .constants import RATINGS
# Create your models here.
RATINGS = [
    ('⭐', '⭐'),
    ('⭐⭐', '⭐⭐'),
    ('⭐⭐⭐', '⭐⭐⭐'),
    ('⭐⭐⭐⭐', '⭐⭐⭐⭐'),
    ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐'),
]

class Quiz(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete = models.CASCADE) 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    choice = models.CharField(choices=RATINGS,max_length=20)
    body = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True) 
    
    def __str__(self):
        return f"Comment by {self.user.username} on {self.quiz.title}"
    

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.TextField()
    opt_1= models.CharField(max_length =250)
    opt_2= models.CharField(max_length =250)
    opt_3= models.CharField(max_length =250)
    opt_4= models.CharField(max_length =250)
    time_limit = models.IntegerField()
    right_opt = models.CharField(max_length=100)

    def __str__(self):
        return self.question
    

class UserAnswerSubmit(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    right_ans = models.CharField(max_length = 250)
    
class userQuizAttempts(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    attemp_time = models.DateTimeField(auto_now_add=True)
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quizistic.</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/css/swiffy-slider.min.css" rel="stylesheet"
        crossorigin="anonymous">

</head>

<body>
    {% include 'navbar.html' with static=static %}
    <section class="">
        <!-- {% for message in messages %}

        <div class="alert {% if 'error' in message.tags %} alert-danger {% else %} alert-{{ message.tags }} {% endif %}  alert-dismissible fade show border mt-3"
            role="alert">
            <strong>{{message.tags}}!</strong> {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

        {% endfor %} -->
        {% block content %}
        {% endblock %}
    </section>




    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider.min.js" crossorigin="anonymous"
        defer></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% for message in messages %}
    <script>

        Swal.fire({
            title: "{{message.tags}}!",
            html: `{{ message }}`,
            icon: "{{message.tags}}"
        });


    </script>
    {% endfor %}


</body>

</html>

templates/footer.html
<footer class="container-fluid mt-auto text-white p-3 bg-danger" style="font-family: 'Poppins', sans-serif;">

    <div class="mt-3 ">
        <h3 class="text-center fw-bold">Want to Connect with us?</h3>
        <p class="text-center">Join us, the quiz game enthusiasts, <br>
            as we dive into the world of trivia and
            brain-teasers.</p>
        <center><a href="{% url 'home' %}" class="btn btn-block btn-outline-light">Get Started</a></center>
        <hr>
    </div>

    <div class="row justify-content-around text-center text-md-start">

        <div class="col-md-2 text-center">
            <h1 class="fw-bold mt-3 "><a class="navbar-brand text-white fw-bolder fs-2"
                    href="{% url 'home' %}">Quizistic.</a></h1>
            <h4>Play Quizzes</h4>
        </div>
        <div class="col-md-2">
            <ul class="list-unstyled">
                <li class="fw-bold my-2">Contents</li>
                <li> <a href="{% url 'home' %}" class="nav-link  text-white">Home</a></li>
                <li> <a href="{% url 'all_quiz' %}" class="nav-link  text-white">Quiz</a></li>
                <li><a href="{% url 'result' %}" class="nav-link  text-white">Result</a> </li>
            </ul>
        </div>
        <div class="col-md-2">
            <ul class="list-unstyled">
                <li class="fw-bold my-2">About</li>
                <li> <a href="#" class="text-decoration-none text-white">Our Projects</a> </li>
                <li> <a href="#" class="text-decoration-none text-white">Goal</a> </li>

            </ul>
        </div>
        <div class="col-md-2">
            <ul class="list-unstyled">
                <li class="fw-bold my-2">Support</li>
                <li> <a href="#" class="text-decoration-none text-white">Contact</a> </li>
                <li> <a href="#" class="text-decoration-none text-white">Support Request</a> </li>
            </ul>
        </div>
        <div class="col-md-2">
            <li class="fw-bold my-2 list-unstyled">Follow us</li>
            <ul class="list-unstyled d-flex justify-content-center justify-content-md-start">
                <li><a href="#" class="text-white"><i class="bi bi-facebook me-2"></i></a></li>
                <li><a href="#" class="text-white"><i class="bi bi-whatsapp mx-2 fa-1x"></i></a></li>
                <li><a href="#" class="text-white"><i class="bi bi-youtube mx-2 fa-1x"></i></a></li>
                <li><a href="#" class="text-white"><i class="bi bi-instagram mx-2 fa-1x"></i></a></li>
            </ul>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12 text-center pt-2">
            <p>&copy; {% now "Y" %} Copyright <a href="#" class="text-white">Quizistic.</a></p>
        </div>
    </div>
    </div>
</footer>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- <div class="row align-items-center  my-5">
    <div class="col-12 col-md-6 order-2 order-md-1 text-center">
        <h2 class="fw-bolder display-5 mt-5">Welcome to <span class="text-danger display-3 fw-bolder ">Quizistic.</span>
        </h2>
        <div class="mt-5">
            <p class="fs-3 ">Make your brain more stonger By playing Quizzes</p>

            {% if user.is_authenticated %}
            <a href="{% url 'all_quiz' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take a Quiz <i
                    class="bi bi-arrow-right"></i></a>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take a Quiz <i
                    class="bi bi-arrow-right "></i></a>
            {% endif %}

        </div>
    </div>
    <div class="col-12 col-md-6 d-flex order-1 order-md-2 justify-content-center">
        <img src="{% static 'images/answer.png' %}" class="w-75" alt="Answer Picture">
    </div>
</div> -->

<div class="swiffy-slider  slider-nav-animation slider-nav-animation-fadein slider-item-first-visible slider-nav-round slider-indicators-outside slider-indicators-round slider-indicators-dark slider-nav-autoplay slider-nav-autopause "
    id="swiffy-animation" data-slider-nav-autoplay-interval="4000">
    <ul class="slider-container bg-body-tertiary py-5" id="container1">
        <li id="slide1" class="slide-visible">
            <div class="my-5 d-flex justify-content-center">
                <div class="row container align-items-center m-0">
                    <div class="col-12 col-md-7 order-2 order-md-1 text-center">
                        <h2 class="fw-bolder display-5 mt-5 mt-md-2">Welcome to <span
                                class="text-danger display-3 fw-bolder ">Quizistic.</span>
                        </h2>
                        <div class="mt-2">
                            <p class="fs-3 ">Make your brain more stonger By playing Quizzes</p>

                            {% if user.is_authenticated %}
                            <a href="{% url 'all_quiz' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take
                                a
                                Quiz <i class="bi bi-arrow-right"></i></a>
                            {% else %}
                            <a href="{% url 'login' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3 ">Take a
                                Quiz
                                <i class="bi bi-arrow-right "></i></a>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col-12 col-md-5 d-flex order-1 order-md-2 justify-content-center">
                        <img src="{% static 'images/brain.svg' %}" class="w-75" alt="Answer Picture">
                    </div>
                </div>
            </div>
        </li>
        <li id="slide2">

            <div class=" my-5 d-flex justify-content-center">
                <div class="row container align-items-center m-0">
                    <div class="col-12 col-md-7 order-2 order-md-1 text-center">
                        <h2 class="fw-bolder display-5 mt-5 mt-md-2">Choose the <span
                                class="text-danger display-3 fw-bolder ">Correct</span> Answer
                        </h2>
                        <div class="mt-2">
                            <p class="fs-3 ">Which will make your points upgraded.</p>

                            {% if user.is_authenticated %}
                            <a href="{% url 'all_quiz' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take
                                a
                                Quiz <i class="bi bi-arrow-right"></i></a>
                            {% else %}
                            <a href="{% url 'login' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take a
                                Quiz
                                <i class="bi bi-arrow-right "></i></a>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col-12 col-md-5 d-flex order-1 order-md-2 justify-content-center">
                        <img src="{% static 'images/answer.png' %}" class="w-75" alt="Answer Picture">
                    </div>
                </div>
            </div>
        </li>
        <li id="slide3">
            <div class="my-5 d-flex justify-content-center">
                <div class="row container align-items-center m-0">
                    <div class="col-12 col-md-7 order-2 order-md-1 text-center">
                        <h2 class="fw-bolder display-5 mt-5 mt-md-2">Think <span
                                class="text-danger display-3 fw-bolder ">Deeply</span>
                        </h2>
                        <div class="mt-2">
                            <p class="fs-3 ">Because deeply thinking can give you success with 90% correct answer.</p>

                            {% if user.is_authenticated %}
                            <a href="{% url 'all_quiz' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take
                                a
                                Quiz <i class="bi bi-arrow-right"></i></a>
                            {% else %}
                            <a href="{% url 'login' %}" class="btn btn-danger rounded-pill fs-5  px-4 py-2 mt-3">Take a
                                Quiz
                                <i class="bi bi-arrow-right "></i></a>
                            {% endif %}

                        </div>
                    </div>
                    <div class="col-12 col-md-5 d-flex order-1 order-md-2 justify-content-center">
                        <img src="{% static 'images/problem-solving.svg' %}" class="w-75" alt="Answer Picture">
                    </div>
                </div>
            </div>
        </li>
    </ul>

    <button type="button" class="slider-nav" aria-label="Go to previous"></button>
    <button type="button" class="slider-nav slider-nav-next" aria-label="Go to next"></button>

    <div class="slider-indicators">
        <button aria-label="Go to slide" class="active "></button>
        <button aria-label=" Go to slide"></button>
        <button aria-label="Go to slide"></button>

    </div>
</div>

<section class="my-5 pb-5">
    <div class="d-flex justify-content-center ">
        <h1 class="display-4 fw-bold border-bottom  border-2 text-center my-3 w-50 py-3">Running Quizzes</h1>
    </div>


    <div class="container">
        <div class="d-flex flex-wrap gap-2 justify-content-center ">
            <a href="{% url 'home' %}" class="btn btn-light ">All Quiz</a>
            {% for cat in categories %}
            <a href="{% url 'home_cat' cat.slug %}" class="btn btn-light ">{{cat.name}}</a>
            {% endfor %}

        </div>
    </div>
    <div class="container mt-5">
        {% if quizzes|length > 0 %}

        <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 row-cols-lg-3 gy-3">

            {% for quiz in quizzes %}
            <div class="col">
                <div class=" card shadow-sm px-0 h-100">
                    <div class="card-body">
                        <h4>{{quiz.title}}</h4>
                        <p class="card-text">Total Questions - {{quiz.question_set.count}}</p>
                        <p class="card-text">{{quiz.description | truncatewords:8}}</p>
                    </div>
                    <div class="card-footer bg-transparent border-0 my-2">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                {% if user.is_authenticated %}
                                <a href="{% url 'question' quiz.id %}" type="button"
                                    class="btn btn-sm btn-outline-danger">Start
                                    Quiz</a>
                                {% else %}
                                <a href="{% url 'login' %}" type="button" class="btn btn-sm btn-outline-danger">Start
                                    Quiz</a>
                                {% endif %}

                            </div>
                            <small class="text-body-secondary">{{quiz.created_at | timesince}} ago</small>
                        </div>
                        <div class="d-flex justify-content-center mt-3">
                            <a href="{% url 'ratings' quiz.id %}"
                                class="text-dark mx-auto btn bg-body-tertiary  shadow-sm rounded-pill py-0  text-decoration-none">
                                Show Ratings <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>

                    </div>

                </div>
            </div>
            {% endfor %}

        </div>
        {% else %}
        <h3 class="text-danger fw-bolder text-center">There is no Quiz available for this Category.</h3>
        {% endif %}

    </div>
    <div class="container  my-5"><a href="{% url 'all_quiz' %}" class="btn btn-sm btn-danger rounded-0 float-end">More
            Quizzes <i class="bi bi-arrow-right "></i></a>
    </div>
</section>
{% endblock %}

templates/loading.html
<div class="row w-25">
    <div class="col-xs-8">
        <div class="progress">
            <div class="progress-bar bg-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                style="width:0%">

            </div>
        </div>
    </div>
</div>

<script>

    var progressBar = document.querySelector('.progress-bar');
    var percentVal = 0;

    window.setInterval(function () {

        percentVal += 20;
        progressBar.style.width = percentVal + '%';
        progressBar.setAttribute("aria-valuenow", percentVal + '%');


        if (percentVal >= 100) {
            percentVal = 0;
        }

    }, 400);


</script>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg shadow-sm ">
    <div class=" container ">
        <a class="navbar-brand text-danger fw-bolder fs-2" href="{% url 'home' %}">Quizistic.</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse gap-2 " id="navbarNavAltMarkup">
            <div class="navbar-nav  ps-lg-5 item-nav ">
                <a class="btn  btn-outline-dark rounded-0 border-0  fw-medium" aria-current="page"
                    href="{% url 'home' %}">Home</a>
                {% if user.is_authenticated %}
                <a class="btn  btn-outline-dark rounded-0 border-0  fw-medium" aria-current="page"
                    href="{% url 'all_quiz' %}">Quiz</a>
                <a class="btn  btn-outline-dark rounded-0 border-0  fw-medium" aria-current="page"
                    href="{% url 'result' %}">Result</a>
                {% endif %}

            </div>
            <div class="navbar-nav  item-nav gap-2 ms-lg-auto 2 align-items-center ">
                {% if user.is_authenticated %}
                <div class="fw-medium ">Welcome, {{ request.user.first_name }} {{ request.user.last_name }} </div>
                <div class="btn-group dropstart" data-bs-hover="dropdown">
                    <button type=" button" class="btn px-0 border-0 rounded-0" data-bs-toggle="dropdown">
                        {% if user.account.profile_image and user.account.profile_image.url %}
                        <img src="{{ user.account.profile_image.url }}" class="profile-pic" alt="Profile Pic"
                            style="border-radius: 50%; height: 45px; width: 45px; object-fit: cover; object-position: 50% 20%; border: 2px solid #1877f2;">
                        {% else %}
                        <img src="{% static 'images/default.png' %}" class="profile-pic" alt="Default Profile Pic"
                            style="border-radius: 50%; height: 45px; width: 45px; object-fit: cover; object-position: 50% 20%; border: 2px solid #1877f2;">
                        {% endif %}
                    </button>
                    <ul class="dropdown-menu mt-5 ">
                        <li><a href="{% url 'profile' %}" class="rounded-0 text-decoration-none"><button
                                    class="dropdown-item " type="button">
                                    <i class="bi bi-person-fill me-2"></i>Profile</button></a></li>
                        <li><a href="{% url 'pass_change' %}" class="rounded-0 text-decoration-none"><button
                                    class="dropdown-item " type="button">
                                    <i class="bi bi-lock-fill me-2"></i></i>Change Password</button></a></li>

                        <li>
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}

                                <button class="dropdown-item " type="submit"">
                                    <i class=" bi bi-box-arrow-left me-2"></i>Logout</button>
                            </form>
                        </li>
                    </ul>
                </div>


                {% else%}
                <a href=" {% url 'register' %}" class="btn btn-outline-danger rounded-0">Sign Up</a>
                <a href="{% url 'login' %}" class="btn btn-danger rounded-0">Login</a>
                {% endif %}

            </div>
        </div>
    </div>

</nav>